### ISSUE TITLE
Unexpected Error - Login not working (first time setup)

### ISSUE THREAD

**Issue by napfkuchen1** [basilfx/homeassistant-biketrax#149]
Hi,

i installed the addon through HACS which went flawless. Restarted HA several times since then. 
Unfortunately i cannot login to Biketrax and get the "Unexpected Error" 
Any Ideas?

Here's the log file

```
Logger: custom_components.biketrax.config_flow
Quelle: custom_components/biketrax/config_flow.py:78
Integration: PowUnity BikeTrax (Dokumentation, Probleme)
Erstmals aufgetreten: 16:10:03 (1 Vorkommnisse)
Zuletzt protokolliert: 16:10:03

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 49, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 220, in get_devices
    return [models.device_from_dict(device) for device in response]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 874, in device_from_dict
    return Device.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 631, in from_dict
    attributes = DeviceAttributes.from_dict(obj.get("attributes"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 555, in from_dict
    passport = from_union([Passport.from_dict, from_none], obj.get("passport"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 30, in from_union
    assert False
           ^^^^^
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/biketrax/config_flow.py", line 78, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/biketrax/config_flow.py", line 42, in validate_input
    await account.update_devices()
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/client.py", line 61, in update_devices
    device.id: device for device in await self.traccar_api.get_devices()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 51, in wrapper
    raise ApiError("Unable to parse API response.") from e
aiobiketrax.exceptions.ApiError: Unable to parse API response.
```

Many Thanks!

**Comment by napfkuchen1** [comment]
As the integration is not visible without logging in I think this is all I got

**Comment by basilfx** [comment]
You might be more successful using the regular logging configuration: https://www.home-assistant.io/integrations/logger/

**Comment by napfkuchen1** [comment]
I think I cant get the output you are needing. This is what is able to be seen in the logs, still

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.biketrax.config_flow
Quelle: custom_components/biketrax/config_flow.py:78
Integration: PowUnity BikeTrax (Dokumentation, Probleme)
Erstmals aufgetreten: 10:50:32 (4 Vorkommnisse)
Zuletzt protokolliert: 11:07:42

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 49, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 220, in get_devices
    return [models.device_from_dict(device) for device in response]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 874, in device_from_dict
    return Device.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 631, in from_dict
    attributes = DeviceAttributes.from_dict(obj.get("attributes"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 555, in from_dict
    passport = from_union([Passport.from_dict, from_none], obj.get("passport"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 30, in from_union
    assert False
           ^^^^^
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/biketrax/config_flow.py", line 78, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/biketrax/config_flow.py", line 42, in validate_input
    await account.update_devices()
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/client.py", line 61, in update_devices
    device.id: device for device in await self.traccar_api.get_devices()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 51, in wrapper
    raise ApiError("Unable to parse API response.") from e
aiobiketrax.exceptions.ApiError: Unable to parse API response.
```

This is what my Logger is configured to:

````
logger:
  default: debug
  logs:
    custom_components.biketrax: debug
    custom_components.aiobiketrax.api: debug
    custom_components.aiobiketrax.api.responses: debug
    custom_components.aiobiketrax.api.client: debug

**Comment by basilfx** [comment]
I see. It fails because the response data is not what is expected. It should be an object, and look like [this](https://github.com/basilfx/aiobiketrax/blob/master/contrib/responses/device.json#L9).

Try to go into the PowUnity app, and change some of the passport details of your bicycle. I presume that will fix it. If not, than I would need the raw responses to know exactly what is in there.

**Comment by basilfx** [comment]
Good to hear! 

PowUnity's API is not so strict and returns all kinds of (unexpected) responses if not properly initialized. It becomes difficult when reverse engineering, sometime ;-)
