### ISSUE TITLE
error after setup.

### ISSUE THREAD

**Issue by gllmlbrt** [basilfx/homeassistant-biketrax#2]
Hey, thanks for making this integration! I am so looking forward to use it. 
I installed and set it up fine, but I get the following error.
I am running 2022.08, hosted/supervised on an ordroid n2.

Logger: custom_components.biketrax.coordinator
Source: custom_components/biketrax/coordinator.py:115
Integration: PowUnity BikeTrax (documentation, issues)
First occurred: 01:06:16 (4 occurrences)
Last logged: 01:08:28

Unexpected error fetching biketrax-<email>-subscription data:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/biketrax/coordinator.py", line 115, in _async_update_data
    await device.update_subscription()
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/client.py", line 167, in update_subscription
    ] = await self._account.admin_api.get_subscription(
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/api.py", line 400, in get_subscription
    return models.subscription_from_dict(response)
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 730, in subscription_from_dict
    return Subscription.from_dict(s)
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 544, in from_dict
    subscription_id = from_none(obj.get("subscriptionId"))
  File "/usr/local/lib/python3.10/site-packages/aiobiketrax/models.py", line 35, in from_none
    assert x is None
AssertionError
`

Let me know if I should pull more logs etc ?

**Comment by Nordicfastware** [comment]
I read from the aiobiketrax library discussion that this may be related to the "from_none" change in the works.

Let me know if there is a way I can test it for you.

**Comment by basilfx** [comment]
@gllmlbrt thanks for reporting the issue.

It is likelike that this issue will be fixed with the next version of `aiobiketrax`, because `subscriptionId` can also be string. I hope to have a new version ready soon.

**Comment by basilfx** [comment]
I've managed to implement everything I want in the next release, including a bunch of fixes. I am testing this version now, and will release it after a few days of testing.
