### ISSUE TITLE
Error : fail config

### ISSUE THREAD

**Issue by viskor** [basilfx/homeassistant-biketrax#92]
Since some day i have an error : Fail configuration.

In log i see : 

```
2023-06-22 08:58:42.915 DEBUG (MainThread) [custom_components.biketrax.coordinator] Device data coordinator updating.
2023-06-22 08:58:44.171 DEBUG (MainThread) [custom_components.biketrax.coordinator] Finished fetching biketrax-XYZ@gmail.com-device data in 1.256 seconds (success: True)
2023-06-22 08:58:44.171 DEBUG (MainThread) [custom_components.biketrax.coordinator] Trip data coordinator updating.
2023-06-22 08:58:44.452 DEBUG (MainThread) [custom_components.biketrax.coordinator] Finished fetching biketrax-XYZ@gmail.com-trip data in 0.281 seconds (success: True)
2023-06-22 08:58:44.452 DEBUG (MainThread) [custom_components.biketrax.coordinator] Subscription data coordinator updating.
2023-06-22 08:58:44.646 DEBUG (MainThread) [custom_components.biketrax.coordinator] Finished fetching biketrax-XYZ@gmail.com-subscription data in 0.193 seconds (success: True)
2023-06-22 08:58:44.646 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry BikeTrax XYZ@gmail.com for biketrax
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/biketrax/__init__.py", line 82, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
2023-06-22 08:58:45.057 ERROR (MainThread) [aiobiketrax.client] Unhandled exception while reading from WebSocket, error counter is 0.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 49, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 278, in post_session
    return models.session_from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 831, in session_from_dict
    return Session.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 157, in from_dict
    token = from_str(obj.get("token"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 13, in from_str
    assert isinstance(x, str)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/client.py", line 100, in update_task
    async for update in self.traccar_api.create_socket():
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 40, in wrapper
    async for x in func(*args, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 72, in wrapper
    async for x in func(*args, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 482, in create_socket
    await self.post_session()
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 51, in wrapper
    raise ApiError("Unable to parse API response.") from e
aiobiketrax.exceptions.ApiError: Unable to parse API response.
```

Can you tell me where is the problem and how solve it?

**Comment by basilfx** [comment]
Can you try one of the following approaches:

1. Add the following to your `configuration.yaml`, and then restart:

```
logger:
  default: warning
  logs:
    aiobiketrax: debug
    aiobiketrax.responses: debug
```

Then send me the response you get back for the `/api/session` endpoint.

2. Sign-in on `https://app.powunity.com`. Then (in Chrome) open the element inspector, go to the network tab and filter for the POST `session` request. Then send me the response.

Be sure to hide sensitive details.

**Comment by viskor** [comment]
I check tomorow :)

**Comment by viskor** [comment]
> Can you try one of the following approaches:
> 
> 1. Add the following to your `configuration.yaml`, and then restart:
> 
> ```
> logger:
>   default: warning
>   logs:
>     aiobiketrax: debug
>     aiobiketrax.responses: debug
> ```
> 
> Then send me the response you get back for the `/api/session` endpoint.
> 
> 2. Sign-in on `https://app.powunity.com`. Then (in Chrome) open the element inspector, go to the network tab and filter for the POST `session` request. Then send me the response. You might need to refresh the page if you cannot find the response.
> 
> ![image](https://user-images.githubusercontent.com/815976/248004568-866a8908-9f76-43a7-a3e2-9d512cebdb3d.png)
> 
> Be sure to hide sensitive details.

Ok i see the error, Hacs was not uptodate and your plugin not uptodate because hacs must be manually update. After update hacs, i have succefully update plugin and work again :)
